// The real bookshelf, cataloged from a photo (IMG_1202.jpeg) Scott took of
// his own shelf and asked to be scanned for every distinct book, film, and
// divination deck on it. See the library scene (src/scenes/library.js) for
// how this becomes a 3D shelf you can look around and click into.
//
// row/col/pos preserve the real shelf's layout — a 4x2 Kallax-style cube
// shelf, row 1 on top — and pos is left-to-right order within that cubby,
// so the scene lays these out in the same order they actually sit in
// Scott's apartment.
//
// A first pass at this catalog was built from the wrong source photo
// (IMG_1192.jpeg, a distorted panorama); this is the corrected version,
// re-read directly from IMG_1202.jpeg (5712x4284, straight-on).
//
// Bibliographic/filmographic data (2026-07-22): Scott asked for ISBNs and
// as much data on each item as could be assembled. Every isbn13/publisher/
// publish_year/pages/translator/editor field below was looked up (Open
// Library, publisher pages, WorldCat-adjacent bookseller listings), not
// guessed — and where a specific edition couldn't be pinned down from the
// spine alone (a title with several active printings, or an ambiguous
// translation), that's recorded in a `note` field rather than silently
// picking one. release_year/runtime_min/country on the film entries were
// looked up the same way; ISBN doesn't apply to films, so those keep their
// Criterion spine numbers (in `creator`) as their identifier instead.
//
// Panel content pass (2026-07-22, same day): Scott asked for writer/
// producer credits on every film, a short excerpt for as many books as
// possible, and a YouTube link to one pivotal scene per film — this is the
// content the read panel actually surfaces now.
//   - `writer` / `producer` on every bluray/bluray entry, researched the same
//     way as the rest of the filmographic data.
//   - `youtube` (a link) + `scene` (what it shows) on every film — picked
//     for being a genuinely pivotal/iconic moment, preferring official
//     studio/Movieclips-style uploads where one existed. Links can rot;
//     that's an accepted tradeoff for linking out to real footage instead
//     of hosting/reproducing it here.
//   - `excerpt` on books/decks where a short, fair-use-scale quotation
//     exists to give (mostly opening lines, matched to the specific
//     translation on the shelf where translation matters). Deliberately
//     NOT added to art/photography/reference books (the Taschen volumes,
//     Japanese Woodblock Prints, Book of Symbols, Art of Atari, the French
//     Laundry cookbooks, Expanding Universe) or to the tarot/alchemy decks
//     — there's no natural "excerpt" for those. Also deliberately skipped
//     for The Lyrics (McCartney) — reproducing song lyrics, even briefly,
//     is a firmer copyright line than a novel's opening sentence.
//
// Scott's own review pass on all of this is still pending — expect
// corrections.
export const libraryItems = [
  { id: 1, type: 'book', title: 'Beowulf', creator: 'trans. Seamus Heaney', row: 1, col: 1, pos: 0, isbn13: '9780393330106', publisher: 'W. W. Norton & Company', translator: 'Seamus Heaney', note: 'Norton standalone paperback edition; Norton Critical Edition variant is 9780393938371', excerpt: 'So. The Spear-Danes in days gone by and the kings who ruled them had courage and greatness. We have heard of those princes’ heroic campaigns. There was Shield Sheafson, scourge of many tribes, this terror of the hall-troops had come far. A foundling to start with, he would flourish later on as his powers waxed and his worth was proved. In the end each clan on the outlying coasts beyond the whale-road had to yield to him and begin to pay tribute. That was one good king.' },
  { id: 2, type: 'book', title: 'Shinto: The Kami Way', creator: 'Sokyo Ono', row: 1, col: 1, pos: 1, isbn13: '9780804819602', publisher: 'Tuttle Publishing', publish_year: 1994, note: 'multiple Tuttle printings exist; also 9780804805254 (1989)' },
  { id: 3, type: 'book', title: 'Água Viva', creator: 'Clarice Lispector', row: 1, col: 1, pos: 2, isbn13: '9780811219907', publisher: 'New Directions', publish_year: 2012, pages: 88, translator: 'Stefan Tobler', note: 'Dissolving plot into pure interior sensation — the same drift toward unstable, perception-first reality that runs through Murakami’s 1Q84.' },
  { id: 4, type: 'book', title: 'Tao Te Ching', creator: 'Lao Tzu', row: 1, col: 1, pos: 3, isbn13: '9780140441314', publisher: 'Penguin Classics', publish_year: 1963, pages: 191, translator: 'D. C. Lau', excerpt: 'The way that can be spoken of is not the constant way; the name that can be named is not the constant name. The nameless was the beginning of heaven and earth; the named was the mother of the myriad creatures. Hence always rid yourself of desires in order to observe its secrets; but always allow yourself to have desires in order to observe its manifestations.' },
  { id: 5, type: 'book', title: 'Faust', creator: 'Johann Wolfgang von Goethe', row: 1, col: 1, pos: 4, isbn13: '9780140449013', publisher: 'Penguin Classics', publish_year: 2005, translator: 'David Constantine', note: 'Faust Part 1; translation edition uncertain from spine alone, several Penguin translations exist (Wayne, Constantine) — flag for Scott' },
  { id: 6, type: 'book', title: 'Alchemy & Mysticism', creator: 'Alexander Roob (Taschen)', row: 1, col: 1, pos: 5, isbn13: '9783836549363', publisher: 'TASCHEN', publish_year: 2014, pages: 575, note: 'edition uncertain, Taschen has reissued this multiple times (1997/2003/2009/2014); flag for Scott. James Merrill’s The Changing Light at Sandover puts the same kind of channeled material into epic poetry instead of reference form.' },
  { id: 7, type: 'book', title: 'The Canterbury Tales', creator: 'Geoffrey Chaucer', row: 1, col: 2, pos: 0, isbn13: '9780140424386', publisher: 'Penguin Classics', publish_year: 2003, pages: 528, translator: 'Nevill Coghill', excerpt: 'When in April the sweet showers fall and pierce the drought of March to the root, and all the veins are bathed in liquor of such power as brings about the engendering of the flower, when also Zephyrus with his sweet breath exhales an air in every grove and heath upon the tender shoots, and the young sun his half-course in the sign of the Ram has run, and the small fowl are making melody that sleep away the night with open eye.' },
  { id: 8, type: 'book', title: 'Paradise Lost', creator: 'John Milton', row: 1, col: 2, pos: 1, isbn13: '9780140424393', publisher: 'Penguin Classics', publish_year: 2003, pages: 512, editor: 'John Leonard', excerpt: 'Of man’s first disobedience, and the fruit of that forbidden tree, whose mortal taste brought death into the world, and all our woe, with loss of Eden, till one greater Man restore us, and regain the blissful seat, sing, Heav’nly Muse.' },
  { id: 9, type: 'book', title: 'Medea and Other Plays', creator: 'Euripides', row: 1, col: 2, pos: 2, isbn13: '9780140449297', publisher: 'Penguin Classics', publish_year: 2003, translator: 'John Davie / Richard Rutherford', note: 'older Vellacott translation is 9780140441291 (1963); edition uncertain, flag for Scott' },
  { id: 10, type: 'book', title: 'The Bacchae and Other Plays', creator: 'Euripides', row: 1, col: 2, pos: 3, isbn13: '9780140447262', publisher: 'Penguin Classics', publish_year: 2006, translator: 'John Davie', note: 'older Vellacott translation is 9780140440447; edition uncertain, flag for Scott' },
  { id: 11, type: 'book', title: 'A Portrait of the Artist as a Young Man', creator: 'James Joyce', row: 1, col: 2, pos: 4, isbn13: '9780142437346', publisher: 'Penguin Classics', publish_year: 2003, note: 'photo shows Penguin Classics Deluxe cover style; newer centennial deluxe edition is 9780143108245 — edition uncertain, flag for Scott. The same Stephen Dedalus gets one long day’s worth of Dublin in Ulysses.', excerpt: 'Once upon a time and a very good time it was there was a moocow coming down along the road and this moocow that was coming down along the road met a nicens little boy named baby tuckoo. His father told him that story: his father looked at him through a glass: he had a hairy face. He was baby tuckoo. The moocow came down the road where Betty Byrne lived: she sold lemon platt. O, the wild rose blossoms on the little green place. He sang that song. That was his song. O, the green wothe botheth.' },
  { id: 12, type: 'book', title: 'The Republic', creator: 'Plato', row: 1, col: 2, pos: 5, isbn13: '9780140449143', publisher: 'Penguin Classics', publish_year: 2003, translator: 'Desmond Lee', excerpt: 'I went down to the Piraeus yesterday with Glaucon, son of Ariston, to pray to the goddess, and also because I wanted to see how they would conduct the festival.', note: 'exact wording of this excerpt not confirmed against the Desmond Lee translation specifically — every translation opens with this same scene, but phrasing varies by translator' },
  { id: 13, type: 'book', title: 'The Symposium', creator: 'Plato', row: 1, col: 2, pos: 6, isbn13: '9780140449273', publisher: 'Penguin Classics', publish_year: 2003, pages: 144, translator: 'Christopher Gill', excerpt: 'Each of us when separated, having one side only, like a flat fish, is but the indenture of a man, and he is always looking for his other half... human nature was originally one and we were a whole, and the desire and pursuit of the whole is called love.', excerpt_from: 'Aristophanes’ speech (trans. Benjamin Jowett, 1871, public domain) — the origin-of-love myth Hedwig and the Angry Inch stages directly as “The Origin of Love”', note: 'Philip K. Dick’s VALIS reenacts this same split-self myth completely literally, dividing its own author into two named characters to investigate one vision. Patrick Harpur’s Daimonic Reality would say the myth was never asking whether the missing half is literally real — that question comes after the more basic one, which is what kind of real means here.' },
  { id: 14, type: 'book', title: 'Phaedrus', creator: 'Plato', row: 1, col: 2, pos: 7, isbn13: '9780140449747', publisher: 'Penguin Classics', publish_year: 2005, translator: 'Christopher Rowe' },
  { id: 15, type: 'book', title: 'The Last Days of Socrates', creator: 'Plato', row: 1, col: 2, pos: 8, isbn13: '9780140449280', publisher: 'Penguin Classics', publish_year: 2003, translator: 'Harold Tarrant / Hugh Tredennick', note: 'contains Euthyphro, Apology, Crito, Phaedo; newer Christopher Rowe translation is 9780140455496 — edition uncertain' },
  { id: 16, type: 'book', title: 'The Epic of Gilgamesh', creator: '', row: 1, col: 2, pos: 9, isbn13: '9780140449198', publisher: 'Penguin Classics', publish_year: 2020, pages: 304, translator: 'Andrew George', note: 'revised edition; earlier printing was 9780140447217', excerpt: 'He who saw the Deep, the country’s foundation, who knew..., was wise in all matters! He saw what was secret, discovered what was hidden, he brought back a tale of before the Deluge. He came a far road, was weary, found peace, and set all his labors on a tablet of stone. He built the rampart of Uruk-the-Sheepfold, of holy Eanna, the sacred storehouse.' },
  { id: 17, type: 'book', title: 'The Theban Plays', creator: 'Sophocles', row: 1, col: 2, pos: 10, isbn13: '9780140444254', publisher: 'Penguin Classics', publish_year: 1984, translator: 'Robert Fagles', note: 'catalog title \'The Theban Plays\' matches Penguin\'s \'The Three Theban Plays\' (Antigone, Oedipus the King, Oedipus at Colonus)', excerpt: 'Oh my children, the new blood of ancient Thebes, why are you here?', excerpt_from: 'opening line of Oedipus the King, one of the three plays in this collection' },
  { id: 18, type: 'book', title: 'Lysistrata and Other Plays', creator: 'Aristophanes', row: 1, col: 2, pos: 11, isbn13: '9780140448146', publisher: 'Penguin Classics', publish_year: 2003, pages: 304, translator: 'Alan H. Sommerstein' },
  { id: 19, type: 'book', title: 'Leaves of Grass', creator: 'Walt Whitman', row: 1, col: 2, pos: 12, isbn13: '9780140421996', publisher: 'Penguin Classics', editor: 'Malcolm Cowley', note: 'first (1855) edition text', excerpt: 'I celebrate myself, and sing myself, and what I assume you shall assume, for every atom belonging to me as good belongs to you. I loafe and invite my soul, I lean and loafe at my ease observing a spear of summer grass.' },
  { id: 20, type: 'book', title: 'Bhagavad Gita', creator: '', row: 1, col: 2, pos: 13, isbn13: '9780140441215', publisher: 'Penguin Classics', publish_year: 1962, translator: 'Juan Mascaró', note: 'newer 2003 edition w/ Simon Brodbeck intro is 9780140449181 — edition uncertain' },
  { id: 21, type: 'book', title: 'Buddhist Scriptures', creator: '', row: 1, col: 2, pos: 14, isbn13: '9780140447583', publisher: 'Penguin Classics', publish_year: 2004, editor: 'Donald S. Lopez Jr.' },
  { id: 22, type: 'book', title: 'Oresteia', creator: 'Aeschylus', row: 1, col: 2, pos: 15, isbn13: '9780140443332', publisher: 'Penguin Classics', publish_year: 1984, translator: 'Robert Fagles', note: 'contains Agamemnon, The Libation Bearers, The Eumenides' },
  { id: 23, type: 'book', title: 'Songs of Innocence and Experience', creator: 'William Blake', row: 1, col: 2, pos: 16, isbn13: '9780192810898', publisher: 'Oxford Paperbacks', editor: 'Geoffrey Keynes', note: 'several editions exist across publishers; could not confirm exact edition from spine alone, flag for Scott', excerpt: 'Piping down the valleys wild, piping songs of pleasant glee, on a cloud I saw a child, and he laughing said to me: “Pipe a song about a lamb!” So I piped with merry cheer. “Piper, pipe that song again.” So I piped: he wept to hear. “Drop thy pipe, thy happy pipe; sing thy songs of happy cheer.” So I sung the same again, while he wept with joy to hear.' },
  { id: 24, type: 'book', title: 'Meditations', creator: 'Marcus Aurelius', row: 1, col: 2, pos: 17, isbn13: '9780140449334', publisher: 'Penguin Classics', publish_year: 2006, translator: 'Martin Hammond', note: '2015 hardcover reissue is 9780141395869' },
  { id: 25, type: 'book', title: 'Chaos: Making a New Science', creator: 'James Gleick', row: 1, col: 2, pos: 18, isbn13: '9780143113454', publisher: 'Penguin Books', publish_year: 2008, pages: 384, note: 'earlier edition 9780140092509' },
  { id: 26, type: 'book', title: 'The Homeric Hymns', creator: '', row: 1, col: 2, pos: 19, isbn13: '9780140437829', publisher: 'Penguin Classics', publish_year: 2003, translator: 'Jules Cashford' },
  { id: 27, type: 'bluray', title: 'The Princess Bride', creator: 'dir. Rob Reiner (Criterion)', row: 1, col: 2, pos: 20, release_year: 1987, runtime_min: 98, country: 'USA', writer: 'William Goldman', producer: 'Andrew Scheinman & Rob Reiner', scene: '“As You Wish”', youtube: 'https://www.youtube.com/watch?v=niul8Hy-3wk' },
  { id: 28, type: 'book', title: 'Three Colours Trilogy: Blue White Red (companion volume)', creator: 'Krzysztof Kieślowski', row: 1, col: 2, pos: 21, isbn13: '9780571178926', publisher: 'Faber and Faber', publish_year: 1998, pages: 291, note: 'screenplay collection: Blue, White, Red' },
  { id: 29, type: 'bluray', title: 'Dekalog', creator: 'Krzysztof Kieślowski · Criterion 637', row: 1, col: 3, pos: 0, release_year: 1989, runtime_min: 572, country: 'Poland', note: '10-part TV series, ~53-58 min per episode', writer: 'Krzysztof Kieślowski & Krzysztof Piesiewicz', producer: 'Ryszard Chutkowski', scene: 'the closing scene of Dekalog: One', youtube: 'https://www.youtube.com/watch?v=glcrCEl5pUU' },
  { id: 30, type: 'bluray', title: 'Do the Right Thing', creator: 'Spike Lee · Criterion 97', row: 1, col: 3, pos: 1, release_year: 1989, runtime_min: 120, country: 'USA', writer: 'Spike Lee', producer: 'Spike Lee', scene: '“Fight the Power”', youtube: 'https://www.youtube.com/watch?v=TQ4y7GPeFBY' },
  { id: 31, type: 'bluray', title: 'Seven Samurai', creator: 'Akira Kurosawa · Criterion 2', row: 1, col: 3, pos: 2, release_year: 1954, runtime_min: 207, country: 'Japan', note: 'The code these samurai live and die by gets tested against Macbeth’s ambition in Throne of Blood, turns gentler and more elegiac in Dreams, and gets transplanted into modern Jersey City in Ghost Dog: The Way of the Samurai.', writer: 'Akira Kurosawa, Shinobu Hashimoto, Hideo Oguni', producer: 'Sojiro Motoki', scene: 'the final battle in the rain', youtube: 'https://www.youtube.com/watch?v=9Q7XXV1dPfU' },
  { id: 32, type: 'bluray', title: 'Dazed and Confused', creator: 'Richard Linklater · Criterion 336', row: 1, col: 3, pos: 3, release_year: 1993, runtime_min: 102, country: 'USA', writer: 'Richard Linklater', producer: 'Richard Linklater, Sean Daniel, James Jacks', scene: '"alright, alright, alright"', youtube: 'https://www.youtube.com/watch?v=oVsSHkukhig' },
  { id: 33, type: 'bluray', title: 'The Tree of Life', creator: 'Terrence Malick · Criterion 942', row: 1, col: 3, pos: 4, release_year: 2011, runtime_min: 139, country: 'USA', note: 'Criterion Blu-ray also includes a 188-min extended cut. Its creation sequence was built with Douglas Trumbull, the visual-effects supervisor behind 2001: A Space Odyssey’s stargate, and sits in conversation with Solaris, Tarkovsky’s own rebuttal to that film’s coldness. Robert Anton Wilson’s Prometheus Rising makes the identical argument about consciousness instead of cinema, and Ted Chiang’s “Understand” (in Stories of Your Life and Others) restages it a third way, as a plot about a mind that climbs pure comprehension only to be undone by an axis it never secured.', writer: 'Terrence Malick', producer: 'Sarah Green, Bill Pohlad, Brad Pitt, Dede Gardner, Grant Hill', scene: 'the creation / universe sequence', youtube: 'https://www.youtube.com/watch?v=1WvuJwMFPz4' },
  { id: 34, type: 'bluray', title: 'A Hard Day\'s Night', creator: 'dir. Richard Lester · Criterion 1104', row: 1, col: 3, pos: 5, release_year: 1964, runtime_min: 87, country: 'UK', writer: 'Alun Owen', producer: 'Walter Shenson', scene: 'the “Can’t Buy Me Love” field sequence', youtube: 'https://www.youtube.com/watch?v=MnQ7-if2mas' },
  { id: 35, type: 'bluray', title: 'Citizen Kane', creator: 'Orson Welles', row: 1, col: 3, pos: 6, release_year: 1941, runtime_min: 119, country: 'USA', writer: 'Herman J. Mankiewicz & Orson Welles', producer: 'Orson Welles', scene: 'the opening, “Rosebud”', youtube: 'https://www.youtube.com/watch?v=fr93wwtiKQM' },
  { id: 36, type: 'bluray', title: 'The Silence of the Lambs', creator: 'Jonathan Demme · Criterion 13', row: 1, col: 3, pos: 7, release_year: 1991, runtime_min: 118, country: 'USA', writer: 'Ted Tally', producer: 'Kenneth Utt, Edward Saxon, Ron Bozman', scene: '“it puts the lotion in the basket”', youtube: 'https://www.youtube.com/watch?v=QRqXBsgnYok' },
  { id: 37, type: 'bluray', title: 'Dr. Strangelove', creator: 'Stanley Kubrick · Criterion 821', row: 1, col: 3, pos: 8, release_year: 1964, runtime_min: 94, country: 'UK/USA', writer: 'Peter George, Stanley Kubrick, Terry Southern', producer: 'Stanley Kubrick', scene: 'Major Kong rides the bomb', youtube: 'https://www.youtube.com/watch?v=snTaSJk0n_Y' },
  { id: 38, type: 'bluray', title: 'Blow-Up', creator: 'Michelangelo Antonioni · Criterion 845', row: 1, col: 3, pos: 9, release_year: 1966, runtime_min: 111, country: 'UK/Italy', writer: 'Tonino Guerra & Michelangelo Antonioni (English dialogue: Edward Bond)', producer: 'Carlo Ponti', scene: 'blowing up the park photographs', youtube: 'https://www.youtube.com/watch?v=Q62gRiUrylw' },
  { id: 39, type: 'bluray', title: 'Repo Man', creator: 'Alex Cox · Criterion 534', row: 1, col: 3, pos: 10, release_year: 1984, runtime_min: 92, country: 'USA', writer: 'Alex Cox', producer: 'Jonathan Wacks & Peter McCarthy', scene: '“A Cosmic Ride,” the closing scene', youtube: 'https://www.youtube.com/watch?v=Q4HY544URjA' },
  { id: 40, type: 'bluray', title: 'Hedwig and the Angry Inch', creator: 'John Cameron Mitchell · Criterion 593', row: 1, col: 3, pos: 11, release_year: 2001, runtime_min: 92, country: 'USA', writer: 'John Cameron Mitchell', producer: 'Christine Vachon, Katie Roumel, Pamela Koffler', note: 'Philip K. Dick’s VALIS reenacts the same split-self myth completely literally, dividing its own author into two people to investigate one vision.', scene: '“Origin of Love”', youtube: 'https://www.youtube.com/watch?v=lEn5E6YCoMA' },
  { id: 41, type: 'bluray', title: 'Throne of Blood', creator: 'Akira Kurosawa', row: 1, col: 3, pos: 12, release_year: 1957, runtime_min: 108, country: 'Japan', note: 'Kurosawa running the same code of honor from Seven Samurai through Macbeth’s ambition instead.', writer: 'Shinobu Hashimoto, Ryūzō Kikushima, Akira Kurosawa, Hideo Oguni', producer: 'Sōjirō Motoki & Akira Kurosawa', scene: 'Washizu’s death by arrows', youtube: 'https://www.youtube.com/watch?v=D-3tI5zLt84' },
  { id: 42, type: 'bluray', title: 'Malcolm X', creator: 'Spike Lee · Criterion 740', row: 1, col: 3, pos: 13, release_year: 1992, runtime_min: 202, country: 'USA', writer: 'Arnold Perl & Spike Lee', producer: 'Marvin Worth & Spike Lee', scene: 'the assassination', youtube: 'https://www.youtube.com/watch?v=W9AI-h4D73k' },
  { id: 43, type: 'bluray', title: 'Inside Llewyn Davis', creator: 'Joel & Ethan Coen · Criterion 794', row: 1, col: 3, pos: 14, release_year: 2013, runtime_min: 105, country: 'USA', writer: 'Joel Coen & Ethan Coen', producer: 'Scott Rudin, Joel Coen, Ethan Coen', scene: 'the “Please Mr. Kennedy” recording session', youtube: 'https://www.youtube.com/watch?v=6WCRAuIcjsc' },
  { id: 44, type: 'bluray', title: 'Dreams', creator: 'Akira Kurosawa · Criterion 842', row: 1, col: 3, pos: 15, full_title: 'Akira Kurosawa\'s Dreams', release_year: 1990, runtime_min: 119, country: 'Japan/USA', note: 'A gentler, more elegiac late-career return to the questions of duty and honor Kurosawa first asked in Seven Samurai.', writer: 'Akira Kurosawa', producer: 'Hisao Kurosawa & Mike Y. Inoue', scene: '“Crows,” the Van Gogh episode', youtube: 'https://www.youtube.com/watch?v=We8NpHPXzwI' },
  { id: 45, type: 'bluray', title: 'The 39 Steps', creator: 'Alfred Hitchcock · Criterion 56', row: 1, col: 3, pos: 16, release_year: 1935, runtime_min: 86, country: 'UK', writer: 'Charles Bennett, Ian Hay, Alma Reville', producer: 'Michael Balcon', scene: 'the closing scene', youtube: 'https://www.youtube.com/watch?v=A2_4BMUvRZk' },
  { id: 46, type: 'bluray', title: 'La Jetée / Sans Soleil', creator: 'Chris Marker · Criterion 387', row: 1, col: 3, pos: 17, release_year: 1962, runtime_min: 28, country: 'France', note: 'La Jetée; paired with Sans Soleil (1983, 100 min) on the same Criterion disc', writer: 'Chris Marker', producer: 'Anatole Dauman', scene: 'the final scene at the airport (La Jetée)', youtube: 'https://www.youtube.com/watch?v=1ibtrxdUBTw' },
  { id: 47, type: 'bluray', title: 'Blood Simple', creator: 'Joel & Ethan Coen (Criterion)', row: 1, col: 4, pos: 0, release_year: 1984, runtime_min: 97, country: 'USA', writer: 'Joel Coen & Ethan Coen', producer: 'Ethan Coen', scene: 'the final scene', youtube: 'https://www.youtube.com/watch?v=38NyXIMtwx4' },
  { id: 48, type: 'bluray', title: 'All That Jazz', creator: 'Bob Fosse (Criterion)', row: 1, col: 4, pos: 1, release_year: 1979, runtime_min: 123, country: 'USA', writer: 'Robert Alan Aurthur & Bob Fosse', producer: 'Robert Alan Aurthur', scene: '“Bye Bye Life,” the finale', youtube: 'https://www.youtube.com/watch?v=4XAQ4vFQEJo' },
  { id: 49, type: 'bluray', title: 'No Country for Old Men', creator: 'Joel & Ethan Coen (Criterion)', row: 1, col: 4, pos: 2, release_year: 2007, runtime_min: 122, country: 'USA', writer: 'Joel Coen & Ethan Coen', producer: 'Scott Rudin, Ethan Coen, Joel Coen', scene: 'the coin toss', youtube: 'https://www.youtube.com/watch?v=opbi7d42s8E' },
  { id: 50, type: 'bluray', title: 'Double Indemnity', creator: 'Billy Wilder (Criterion)', row: 1, col: 4, pos: 3, release_year: 1944, runtime_min: 107, country: 'USA', writer: 'Billy Wilder & Raymond Chandler', producer: 'Buddy DeSylva & Joseph Sistrom', scene: 'the ending / the confession', youtube: 'https://www.youtube.com/watch?v=8nYPCDXHuPs' },
  { id: 51, type: 'bluray', title: 'Tokyo Story', creator: 'Yasujiro Ozu (Criterion)', row: 1, col: 4, pos: 4, release_year: 1953, runtime_min: 136, country: 'Japan', note: 'Its quiet acceptance of neglect and mortality plays like wabi-sabi turned into a plot — see In Praise of Shadows on the same shelf.', writer: 'Kogo Noda & Yasujirō Ozu', producer: 'Takeshi Yamamoto', scene: '“isn’t life disappointing?”', youtube: 'https://www.youtube.com/watch?v=h_s_B3kVIFA' },
  { id: 52, type: 'bluray', title: '8½', creator: 'Federico Fellini (Criterion)', row: 1, col: 4, pos: 5, release_year: 1963, runtime_min: 138, country: 'Italy/France', writer: 'Ennio Flaiano, Tullio Pinelli, Federico Fellini, Brunello Rondi', producer: 'Angelo Rizzoli', scene: 'the opening dream sequence', youtube: 'https://www.youtube.com/watch?v=c6CgffwpXmY' },
  { id: 53, type: 'bluray', title: 'Solaris', creator: 'Andrei Tarkovsky (Criterion)', row: 1, col: 4, pos: 6, release_year: 1972, runtime_min: 167, country: 'USSR', note: 'Tarkovsky called Kubrick’s 2001: A Space Odyssey “cold” and “phony” and built this partly as a rebuttal — swapping Kubrick’s awe for grief. Malick’s The Tree of Life later triangulates both, borrowing 2001’s own effects supervisor for its creation sequence.', writer: 'Friedrich Gorenstein & Andrei Tarkovsky', producer: 'Vyacheslav Tarasov', scene: 'the ending', youtube: 'https://www.youtube.com/watch?v=wKiRIIO8WIU' },
  { id: 54, type: 'bluray', title: 'Ghost Dog: The Way of the Samurai', creator: 'Jim Jarmusch (Criterion)', row: 1, col: 4, pos: 7, release_year: 1999, runtime_min: 116, country: 'USA/France/Japan/Germany', note: 'Jarmusch transplants Kurosawa’s warrior code — most directly Seven Samurai’s — onto a hitman living by the Hagakure in modern Jersey City.', writer: 'Jim Jarmusch', producer: 'Richard Guay & Jim Jarmusch', scene: 'swords on the roof / park scene', youtube: 'https://www.youtube.com/watch?v=xAlBlavGaB8' },
  { id: 55, type: 'bluray', title: 'F for Fake', creator: 'Orson Welles (Criterion)', row: 1, col: 4, pos: 8, release_year: 1973, runtime_min: 89, country: 'France/Iran/West Germany', writer: 'Orson Welles & Oja Kodar', producer: 'François Reichenbach, Dominique Antoine, Richard Drewett', scene: 'the Chartres Cathedral meditation', youtube: 'https://www.youtube.com/watch?v=erj8lO8aYog' },
  { id: 56, type: 'bluray', title: 'Miller\'s Crossing', creator: 'Joel & Ethan Coen (Criterion)', row: 1, col: 4, pos: 9, release_year: 1990, runtime_min: 115, country: 'USA', writer: 'Joel Coen & Ethan Coen', producer: 'Ethan Coen', scene: '“look into your heart” (Bernie in the forest)', youtube: 'https://www.youtube.com/watch?v=GJSSkr0JpAE' },
  { id: 57, type: 'bluray', title: 'The Right Stuff', creator: 'Philip Kaufman (Kino Lorber Studio Classics)', row: 1, col: 4, pos: 10, release_year: 1983, runtime_min: 192, country: 'USA', writer: 'Philip Kaufman', producer: 'Robert Chartoff & Irwin Winkler', scene: '“no bucks, no Buck Rogers”', youtube: 'https://www.youtube.com/watch?v=a7rGA0Zv8R4' },
  { id: 58, type: 'bluray', title: 'Barton Fink', creator: 'Joel & Ethan Coen', row: 1, col: 4, pos: 11, release_year: 1991, runtime_min: 116, country: 'USA', writer: 'Ethan Coen & Joel Coen', producer: 'Ethan Coen', scene: 'the ending, “you’re a write-off”', youtube: 'https://www.youtube.com/watch?v=yeBM3nwwmlE' },
  { id: 59, type: 'bluray', title: 'The Maya Deren Collection', creator: '', row: 1, col: 4, pos: 12, note: 'compilation of Maya Deren\'s short experimental films (incl. Meshes of the Afternoon, 1943, w/ Alexander Hammid; At Land; Ritual in Transfigured Time) — no single release-year/runtime applies to the collection as a whole; writer/producer/scene/youtube below are for Meshes of the Afternoon specifically, the best-known film in the set', writer: 'Maya Deren', producer: 'Maya Deren', scene: 'Meshes of the Afternoon (full 14-min short)', youtube: 'https://www.youtube.com/watch?v=bjtLgNpv5AQ' },
  { id: 60, type: 'bluray', title: 'North by Northwest', creator: 'Alfred Hitchcock (4K UHD)', row: 1, col: 4, pos: 13, release_year: 1959, runtime_min: 136, country: 'USA', writer: 'Ernest Lehman', producer: 'Alfred Hitchcock', scene: 'the crop duster attack', youtube: 'https://www.youtube.com/watch?v=TtbOConPflA' },
  { id: 61, type: 'bluray', title: 'Vertigo', creator: 'Alfred Hitchcock (4K UHD)', row: 1, col: 4, pos: 14, release_year: 1958, runtime_min: 128, country: 'USA', writer: 'Alec Coppel & Samuel Taylor', producer: 'Alfred Hitchcock', scene: 'the bell tower ending', youtube: 'https://www.youtube.com/watch?v=GjPCk494e5Q' },
  { id: 62, type: 'bluray', title: 'GoodFellas', creator: 'Martin Scorsese (4K UHD)', row: 1, col: 4, pos: 15, release_year: 1990, runtime_min: 146, country: 'USA', writer: 'Nicholas Pileggi & Martin Scorsese', producer: 'Irwin Winkler', scene: '“funny how? funny like a clown?”', youtube: 'https://www.youtube.com/watch?v=tl-D128yaMA' },
  { id: 63, type: 'bluray', title: '2001: A Space Odyssey', creator: 'Stanley Kubrick, 50th Anniversary Edition (4K UHD)', row: 1, col: 4, pos: 16, release_year: 1968, runtime_min: 149, country: 'UK/USA', note: 'runtime varies by cut across sources (139-161 min); 149 is the commonly cited general-release figure. Its stargate sequence was built by visual-effects supervisor Douglas Trumbull, who came out of retirement decades later to build The Tree of Life’s creation sequence for Malick — and Tarkovsky’s Solaris was conceived partly as a rebuttal to this film’s coldness.', writer: 'Stanley Kubrick & Arthur C. Clarke', producer: 'Stanley Kubrick', scene: 'HAL refuses: “I’m sorry, Dave, I’m afraid I can’t do that”', youtube: 'https://www.youtube.com/watch?v=Wy4EfdnMZ5g' },
  { id: 64, type: 'bluray', title: 'Fargo', creator: 'Joel & Ethan Coen, 2-disc set (4K UHD)', row: 1, col: 4, pos: 17, release_year: 1996, runtime_min: 98, country: 'USA/UK', writer: 'Joel Coen & Ethan Coen', producer: 'Ethan Coen', scene: 'the wood chipper', youtube: 'https://www.youtube.com/watch?v=0YzsWVUO-_o' },
  { id: 65, type: 'bluray', title: 'The Big Lebowski', creator: 'Joel & Ethan Coen (4K UHD)', row: 1, col: 4, pos: 18, release_year: 1998, runtime_min: 117, country: 'USA', writer: 'Joel Coen & Ethan Coen', producer: 'Ethan Coen', scene: '“that rug really tied the room together”', youtube: 'https://www.youtube.com/watch?v=uGK4x4tqPIY' },
  { id: 66, type: 'bluray', title: 'Close Encounters of the Third Kind', creator: 'Steven Spielberg (4K UHD)', row: 1, col: 4, pos: 19, release_year: 1977, runtime_min: 135, country: 'USA', note: 'theatrical cut; Special Edition 132 min, Director\'s Cut 137 min — cut uncertain', writer: 'Steven Spielberg', producer: 'Julia Phillips & Michael Phillips', scene: 'communicating with the mothership', youtube: 'https://www.youtube.com/watch?v=S4PYI6TzqYk' },
  { id: 67, type: 'bluray', title: 'Chinatown', creator: 'Roman Polanski (4K UHD)', row: 1, col: 4, pos: 20, release_year: 1974, runtime_min: 130, country: 'USA', writer: 'Robert Towne', producer: 'Robert Evans', scene: '“my sister, my daughter”', youtube: 'https://www.youtube.com/watch?v=wnrdetFAo1o' },
  { id: 68, type: 'bluray', title: 'Reservoir Dogs', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 21, release_year: 1992, runtime_min: 99, country: 'USA', writer: 'Quentin Tarantino', producer: 'Lawrence Bender, Richard N. Gladstein, Monte Hellman, Harvey Keitel, Ronna B. Wallace', scene: '“Stuck in the Middle With You”', youtube: 'https://www.youtube.com/watch?v=PGqB6JIUzBo' },
  { id: 69, type: 'bluray', title: 'Pulp Fiction', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 22, release_year: 1994, runtime_min: 154, country: 'USA', writer: 'Quentin Tarantino (story w/ Roger Avary)', producer: 'Lawrence Bender', scene: '“Royale with Cheese”', youtube: 'https://www.youtube.com/watch?v=6Pkq_eBHXJ4' },
  { id: 70, type: 'bluray', title: 'Kill Bill Vol. 1', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 23, release_year: 2003, runtime_min: 111, country: 'USA', writer: 'Quentin Tarantino', producer: 'Lawrence Bender', scene: 'showdown at the House of Blue Leaves', youtube: 'https://www.youtube.com/watch?v=EajaioMj-NA' },
  { id: 71, type: 'bluray', title: 'Kill Bill Vol. 2', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 24, release_year: 2004, runtime_min: 137, country: 'USA', writer: 'Quentin Tarantino', producer: 'Lawrence Bender', scene: 'the Five Point Palm Exploding Heart Technique', youtube: 'https://www.youtube.com/watch?v=NL7nLSSSWjw' },
  { id: 72, type: 'book', title: 'Rosencrantz & Guildenstern Are Dead', creator: 'Tom Stoppard', row: 2, col: 1, pos: 0, isbn13: '9780802132758', publisher: 'Grove Press', publish_year: 1994, note: '50th-anniversary edition is 9780802126214 — edition uncertain', excerpt: '(A coin spins in the air, comes down.) GUIL: Heads. ROS: Heads.' },
  { id: 73, type: 'book', title: 'Gödel, Escher, Bach: An Eternal Golden Braid', creator: 'Douglas R. Hofstadter', row: 2, col: 1, pos: 1, isbn13: '9780465026562', publisher: 'Basic Books', publish_year: 1999, pages: 824, note: '20th-anniversary edition. The self-referential “strange loop” this book spends 800 pages on is the same shape as the sentence Finnegans Wake leaves open at both ends.' },
  { id: 74, type: 'book', title: 'wabi sabi: Understanding the Zen Philosophy of Beauty', creator: 'Andrew Juniper (Tuttle)', row: 2, col: 1, pos: 2, isbn13: '9780804834827', publisher: 'Tuttle Publishing', publish_year: 2003, pages: 176, full_title: 'Wabi Sabi: The Japanese Art of Impermanence' },
  { id: 75, type: 'book', title: 'In Praise of Shadows', creator: 'Jun\'ichirō Tanizaki', row: 2, col: 1, pos: 3, isbn13: '9780918172020', publisher: 'Leete\'s Island Books', publish_year: 1977, pages: 56, translator: 'Thomas J. Harper / Edward G. Seidensticker', note: 'Ozu’s Tokyo Story narrativizes the same impermanence and quiet dignity this essay describes.' },
  { id: 76, type: 'book', title: 'Kieślowski on Kieślowski', creator: 'ed. Danusia Stok', row: 2, col: 1, pos: 4, isbn13: '9780571173280', publisher: 'Faber and Faber', publish_year: 1993, pages: 268, editor: 'Danusia Stok' },
  { id: 77, type: 'book', title: 'Three Colours Trilogy: Blue, White, Red (screenplays)', creator: 'Krzysztof Kieślowski & Krzysztof Piesiewicz', row: 2, col: 1, pos: 5, note: '= id 28 (Three Colours Trilogy screenplay book), likely a duplicate sighting across cubbies rather than two separate copies — flag for Scott to confirm whether one of these two catalog entries should be removed' },
  { id: 78, type: 'book', title: 'Gravity\'s Rainbow', creator: 'Thomas Pynchon', row: 2, col: 1, pos: 6, isbn13: '9780143039945', publisher: 'Penguin Classics Deluxe', publish_year: 2006, note: 'cover by Frank Miller; earlier Penguin edition 9780140188592 — edition uncertain. Robert Anton Wilson’s Everything Is Under Control turns this same paranoid pattern-finding into a straight-faced encyclopedia.', excerpt: 'A screaming comes across the sky. It has happened before, but there is nothing to compare it to now.' },
  { id: 79, type: 'book', title: 'Collected Fictions', creator: 'Jorge Luis Borges (Penguin Classics Deluxe)', row: 2, col: 1, pos: 7, isbn13: '9780140286809', publisher: 'Penguin Classics Deluxe', publish_year: 1999, translator: 'Andrew Hurley', excerpt: 'I owe the discovery of Uqbar to the conjunction of a mirror and an encyclopedia. Bioy Casares had come to dinner at my house that evening, and we had lost all track of time in a vast debate over the way one might go about composing a first-person novel whose narrator would omit or distort things and engage in all sorts of contradictions, so that a few of the book’s readers — a very few — might divine the horrifying or banal truth.', excerpt_from: 'opening of “Tlön, Uqbar, Orbis Tertius,” one story in this collection', note: 'Robert Anton Wilson’s Everything Is Under Control catalogs the same collective-belief-made-real phenomenon as nonfiction instead of a short story.' },
  { id: 80, type: 'book', title: 'The Iliad', creator: 'Homer, trans. Robert Fagles (Penguin Classics Deluxe)', row: 2, col: 1, pos: 8, isbn13: '9780140275360', publisher: 'Penguin Classics Deluxe', publish_year: 1998, translator: 'Robert Fagles', note: 'Virgil rebuilt this poem’s war half into the second six books of the Aeneid.', excerpt: 'Rage—Goddess, sing the rage of Peleus’ son Achilles, murderous, doomed, that cost the Achaeans countless losses.' },
  { id: 81, type: 'book', title: 'The Odyssey', creator: 'Homer, trans. Robert Fagles (Penguin Classics Deluxe)', row: 2, col: 1, pos: 9, isbn13: '9780140268867', publisher: 'Penguin Classics Deluxe', publish_year: 1997, pages: 541, translator: 'Robert Fagles', note: 'Virgil rebuilt this poem’s wandering-hero half into the first six books of the Aeneid.', excerpt: 'Sing to me of the man, Muse, the man of twists and turns driven time and again off course, once he had plundered the hallowed heights of Troy.' },
  { id: 82, type: 'book', title: 'The Aeneid', creator: 'Virgil, trans. Robert Fagles (Penguin Classics Deluxe)', row: 2, col: 1, pos: 10, isbn13: '9780143105138', publisher: 'Penguin Classics Deluxe', publish_year: 2008, translator: 'Robert Fagles', note: 'Virgil built this poem as a deliberate answer to Homer — its first half a wandering-hero story modeled on the Odyssey, its second half a war story modeled on the Iliad. Dante later borrowed Virgil himself as a character, his guide through the Inferno in The Divine Comedy.', excerpt: 'Wars and a man I sing—an exile driven on by Fate, he was the first to flee the coast of Troy, destined to reach Lavinian shores and Italian soil.' },
  { id: 83, type: 'book', title: 'Dune', creator: 'Frank Herbert', row: 2, col: 2, pos: 0, isbn13: '9780441172719', publisher: 'Ace Books', publish_year: 1990, note: 'photo shows a stylized/modern cover, not the 1965 first-printing; exact reissue/edition uncertain, flag for Scott', excerpt: 'In the week before their departure to Arrakis, when all the final scurrying about had reached a nearly unbearable frenzy, an old crone came to visit the mother of the boy, Paul.' },
  { id: 84, type: 'book', title: 'The Complete Stories', creator: 'Clarice Lispector', row: 2, col: 2, pos: 1, isbn13: '9780811219631', publisher: 'New Directions', publish_year: 2015, pages: 645, translator: 'Katrina Dodson', editor: 'Benjamin Moser' },
  { id: 85, type: 'book', title: 'Ulysses', creator: 'James Joyce', row: 2, col: 2, pos: 2, isbn13: '9780679722762', publisher: 'Vintage International', publish_year: 1990, pages: 783, note: '"complete and unabridged, as corrected and reset in 1961". Its hero picks up where A Portrait of the Artist as a Young Man’s Stephen Dedalus left off; Joyce’s next and final book, Finnegans Wake, gives up on linear time — and this book’s single day — altogether.', excerpt: 'Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed. A yellow dressing gown, ungirdled, was sustained gently behind him on the mild morning air. He held the bowl aloft and intoned: —Introibo ad altare Dei. Halted, he peered down the dark winding stairs and called out coarsely: —Come up, Kinch! Come up, you fearful jesuit!' },
  { id: 86, type: 'book', title: '1Q84', creator: 'Haruki Murakami', row: 2, col: 2, pos: 3, isbn13: '9780307476463', publisher: 'Vintage International', publish_year: 2013, pages: 1184, translator: 'Jay Rubin / Philip Gabriel', note: 'single-volume omnibus edition; a 3-volume boxed set also exists (9780345802934). Its blurred line between inner perception and outer reality has a quieter ancestor in Clarice Lispector’s Água Viva.', excerpt: 'Don’t let appearances fool you. There’s always only one reality.', excerpt_from: 'the taxi driver’s line to Aomame, early in Book One — not the literal opening sentence' },
  { id: 87, type: 'book', title: 'Near to the Wild Heart', creator: 'Clarice Lispector', row: 2, col: 2, pos: 4, isbn13: '9780811220026', publisher: 'New Directions', publish_year: 2012, translator: 'Alison Entrekin', note: 'earlier Giovanni Pontiero translation is 9780811211390/9780811211406 — edition uncertain', excerpt: 'There were many good feelings. Climbing the hill, stopping at the top and, without looking, feeling the ground covered behind her, the farm in the distance.' },
  { id: 88, type: 'book', title: 'The Crying of Lot 49', creator: 'Thomas Pynchon', row: 2, col: 2, pos: 5, isbn13: '9780060913076', publisher: 'Harper Perennial', publish_year: 2006, note: 'Harper Perennial Olive Editions reissue is 9780061849923 — edition uncertain', excerpt: 'One summer afternoon Mrs Oedipa Maas came home from a Tupperware party whose hostess had put perhaps too much kirsch in the fondue to find that she, Oedipa, had been named executor... of the estate of one Pierce Inverarity.' },
  { id: 89, type: 'book', title: 'Finnegans Wake', creator: 'James Joyce', row: 2, col: 2, pos: 6, isbn13: '9780141181264', publisher: 'Penguin Classics', publish_year: 1999, pages: 672, note: 'Penguin Modern Classics variant 9780141183114 also exists — edition uncertain. Its opening line completes the sentence its own last line leaves hanging mid-thought — the same shape Douglas Hofstadter calls a “strange loop” in Gödel, Escher, Bach.', excerpt: 'riverrun, past Eve and Adam’s, from swerve of shore to bend of bay, brings us by a commodius vicus of recirculation back to Howth Castle and Environs. Sir Tristram, violer d’amores, fr’over the short sea, had passencore rearrived from North Armorica on this side the scraggy isthmus of Europe Minor to wielderfight his penisolate war...' },
  { id: 90, type: 'book', title: 'The Metamorphoses', creator: 'Ovid (Everyman\'s Library)', row: 2, col: 2, pos: 7, isbn13: '9780140447897', publisher: 'Penguin Classics', publish_year: 2004, translator: 'David Raeburn', note: 'catalog lists creator as Everyman\'s Library, but this Raeburn translation is a Penguin Classics edition — could not confirm a matching Everyman\'s printing, flag for Scott' },
  { id: 91, type: 'book', title: 'The Divine Comedy', creator: 'Dante Alighieri (Everyman\'s Library)', row: 2, col: 2, pos: 8, isbn13: '9780679433132', publisher: 'Everyman\'s Library', publish_year: 1995, translator: 'Allen Mandelbaum', note: 'single-volume Inferno/Purgatorio/Paradiso; UK edition is 9781857151831. Dante’s guide through the Inferno is Virgil, borrowed in as a character from the Aeneid.', excerpt: 'When I had journeyed half of our life’s way, I found myself within a shadowed forest, for I had lost the path that does not stray.' },
  { id: 92, type: 'book', title: 'Japanese Woodblock Prints, 1680–1938', creator: 'Andreas Marks (Taschen 40 series)', row: 2, col: 3, pos: 0, isbn13: '9783836563369', publisher: 'TASCHEN', note: 'full title \'Japanese Woodblock Prints, 1680-1938\'; multiple print runs exist (40th anniv. ed. is 9783836587532) — edition uncertain' },
  { id: 93, type: 'book', title: 'The Book of Symbols: Reflections on Archetypal Images', creator: 'Archive for Research in Archetypal Symbolism (Taschen)', row: 2, col: 3, pos: 1, isbn13: '9783836514484', publisher: 'TASCHEN', publish_year: 2010, pages: 808, editor: 'Ami Ronnberg / Kathleen Martin, for ARAS' },
  { id: 94, type: 'book', title: 'The Beastie Boys Book', creator: 'Michael Diamond & Adam Horovitz (Spiegel & Grau)', row: 2, col: 3, pos: 2, isbn13: '9780812995541', publisher: 'Spiegel & Grau', note: 'UK Faber & Faber edition is 9780571308040 — edition uncertain', excerpt: 'I loved MCA. He was a renegade. He seemed to live life at a million miles an hour, curious about everything, folding his experiences into his creative output.' },
  { id: 95, type: 'book', title: 'The Library of Esoterica: Sacred Sites', creator: 'Taschen', row: 2, col: 3, pos: 3, isbn13: '9783836590600', publisher: 'TASCHEN', publish_year: 2024, pages: 520, editor: 'Jessica Hundley', series: 'The Library of Esoterica' },
  { id: 96, type: 'book', title: 'The Library of Esoterica: Astrology', creator: 'Taschen', row: 2, col: 3, pos: 4, isbn13: '9783836579889', publisher: 'TASCHEN', publish_year: 2020, editor: 'Andrea Richards / Jessica Hundley', series: 'The Library of Esoterica, vol. 2' },
  { id: 97, type: 'book', title: 'The Library of Esoterica: Plant Magick', creator: 'Taschen', row: 2, col: 3, pos: 5, isbn13: '9783836585644', publisher: 'TASCHEN', publish_year: 2022, pages: 520, editor: 'Jessica Hundley', series: 'The Library of Esoterica, vol. 4' },
  { id: 98, type: 'book', title: 'The Library of Esoterica: Tarot', creator: 'Taschen', row: 2, col: 3, pos: 6, isbn13: '9783836579872', publisher: 'TASCHEN', publish_year: 2020, pages: 520, editor: 'Jessica Hundley', series: 'The Library of Esoterica, vol. 1' },
  { id: 99, type: 'divination_box', title: 'The Wild Unknown Tarot', creator: 'Kim Krans', row: 2, col: 3, pos: 7, isbn13: '9780062466594', publisher: 'HarperElixir', publish_year: 2016, pages: 208, note: '78-card deck + guidebook, official keepsake box set' },
  { id: 100, type: 'divination_box', title: 'The Wild Unknown Alchemy', creator: 'Kim Krans', row: 2, col: 3, pos: 8, isbn13: '9781797212579', publisher: 'Chronicle Books', publish_year: 2022, note: 'deck + guidebook, official keepsake box set' },
  { id: 101, type: 'book', title: 'The Library of Esoterica: Witchcraft', creator: 'Taschen', row: 2, col: 4, pos: 0, isbn13: '9783836585606', publisher: 'TASCHEN', pages: 520, editor: 'Jessica Hundley / Pam Grossman', series: 'The Library of Esoterica, vol. 3' },
  { id: 102, type: 'book', title: 'William Shakespeare: Complete Works', creator: 'ed. Jonathan Bate & Eric Rasmussen, RSC 2nd ed. (Modern Library)', row: 2, col: 4, pos: 1, isbn13: '9780593230312', publisher: 'Modern Library', publish_year: 2022, editor: 'Jonathan Bate / Eric Rasmussen', note: '2nd edition, developed with the Royal Shakespeare Company — no single excerpt chosen, given how many plays this volume contains' },
  { id: 103, type: 'book', title: 'The Lyrics: 1956 to the Present', creator: 'Paul McCartney, ed. Paul Muldoon (Liveright)', row: 2, col: 4, pos: 2, isbn13: '9781631492563', publisher: 'Liveright / W. W. Norton', publish_year: 2021, pages: 960, editor: 'Paul Muldoon', note: 'hardcover; paperback is 9781324094098 (624pp, 2023) — edition uncertain; deliberately no lyric excerpt here, since reproducing song lyrics is a firmer copyright line than a novel’s opening line. The Beatles Anthology gives the group’s own fuller, multi-voiced version of this same self-telling.' },
  { id: 104, type: 'book', title: 'Art of Atari', creator: 'Tim Lapetino (Dynamite)', row: 2, col: 4, pos: 3, isbn13: '9781524101039', publisher: 'Dynamite Entertainment', publish_year: 2016, pages: 352, creator_full: 'Tim Lapetino, with Robert V. Conte' },
  { id: 105, type: 'book', title: 'The French Laundry Cookbook', creator: 'Thomas Keller (Artisan)', row: 2, col: 4, pos: 4, isbn13: '9781579651268', publisher: 'Artisan', publish_year: 1999, pages: 336, creator_full: 'Thomas Keller, with Michael Ruhlman and Susie Heller' },
  { id: 106, type: 'book', title: 'The French Laundry, Per Se', creator: 'Thomas Keller (Artisan)', row: 2, col: 4, pos: 5, isbn13: '9781579658496', publisher: 'Artisan', publish_year: 2020, pages: 400, full_title: 'The French Laundry, Per Se' },
  { id: 107, type: 'book', title: 'Expanding Universe: Photographs from the Hubble Space Telescope', creator: 'Taschen', row: 2, col: 4, pos: 6, isbn13: '9783836549226', publisher: 'TASCHEN', pages: 260, creator_full: 'essay by Owen Edwards, interview with Zoltan Levay', note: '25th-anniversary edition; a 30th-anniversary edition with new images also exists — edition uncertain' },

  // Added 2026-07-23: 13 more books, from ISBNs Scott provided directly
  // rather than read off a shelf photo. Placement wasn't cataloged from a
  // real photo this time -- Scott: "I don't care about exact placement,
  // randomize them" -- so row/col/pos below are arbitrary (spread across
  // the existing book cubbies, never the film-only cubbies), not a record
  // of where these physically sit.
  { id: 108, type: 'book', title: 'The Changing Light at Sandover', creator: 'James Merrill', row: 2, col: 1, pos: 100, isbn13: '9780679410836', publisher: 'Knopf', publish_year: 1992, pages: 560, note: 'a 560-page epic assembled from twenty-five years of Ouija-board transcripts. The epigraph on Blood Treachery, the Mage sourcebook Scott co-wrote, is drawn from this book. Shelved not far from Alchemy & Mysticism and the Library of Esoterica series, which take the same kind of channeled material as reference instead of epic verse. Patrick Harpur’s Daimonic Reality gives the board itself a name for what it might be: neither proof of spirits nor merely two men’s shared imagination, but a third thing disclosed through both at once. Ephraim, early in the poem, names the place he speaks from — the same name, “the Surround,” Scott has used in his own private cosmology since at least 2003.', excerpt: 'AM I IN YR ROOM SO ARE ALL YR DEAD WHO HAVE NOT GONE INTO OTHER BODIES… NOW DO U UNDERSTAND WHAT HEAVEN IS IT IS THE SURROUND OF THE LIVING' },
  { id: 109, type: 'book', title: 'The Beatles Anthology', creator: 'The Beatles', row: 2, col: 4, pos: 100, isbn13: '9780811826846', publisher: 'Chronicle Books', publish_year: 2000, pages: 368, note: 'an authorized oral history assembled from interviews with Paul McCartney, George Harrison, and Ringo Starr (plus archival tape of John Lennon) — a fuller group self-telling than The Lyrics gives from McCartney alone.' },
  { id: 110, type: 'book', title: 'VALIS', creator: 'Philip K. Dick', row: 1, col: 1, pos: 100, isbn13: '9780547572413', publisher: 'Mariner Books', publish_year: 2011, pages: 271, note: 'first published 1981. Dick splits himself into a narrator (Phil) and an alter ego (Horselover Fat) to write about his own gnostic vision — his own version of the split self Aristophanes describes in the Symposium, and that Hedwig sings about elsewhere on this shelf.', excerpt: 'Horselover Fat’s nervous breakdown began the day he got the phone call from Gloria asking if he had any Nembutals.' },
  { id: 111, type: 'book', title: 'Pale Fire', creator: 'Vladimir Nabokov', row: 2, col: 2, pos: 100, isbn13: '9780679723424', publisher: 'Vintage International', publish_year: 1989, pages: 315, note: 'first published 1962; a 999-line poem followed by a commentary whose annotator, not the poet, turns out to be the real subject — shelved beside Lolita, Nabokov’s other novel here.', excerpt: 'I was the shadow of the waxwing slain / By the false azure in the windowpane;' },
  { id: 112, type: 'book', title: 'Angels in America: A Gay Fantasia on National Themes', creator: 'Tony Kushner', row: 1, col: 2, pos: 100, isbn13: '9781559367691', publisher: 'Theatre Communications Group', publish_year: 2013, note: 'revised and complete edition, Millennium Approaches and Perestroika in one volume. Scott’s own The L.A. Project takes its epigraph from this play: “Not Physics but Ecstatics Makes the Engine Run.”', excerpt: 'Hello and good morning. I am Rabbi Isidor Chemelwitz of the Bronx Home for Aged Hebrews.' },
  { id: 113, type: 'book', title: 'The Book of the SubGenius', creator: 'Rev. Ivan Stang / SubGenius Foundation', row: 2, col: 3, pos: 100, isbn13: '9780671638108', publisher: 'Simon & Schuster (Fireside)', publish_year: 1987, pages: 184, note: 'the source scripture of “Slack” as a concept — the Church of the SubGenius’s central virtue, and almost certainly where that word entered Scott’s own private vocabulary for it. A second volume, Revelation X, sits beside it here.' },
  { id: 114, type: 'book', title: 'Revelation X: The "Bob" Apocryphon', creator: 'ed. Ivan Stang / SubGenius Foundation', row: 2, col: 3, pos: 101, isbn13: '9780671770068', publisher: 'Simon & Schuster (Fireside)', publish_year: 1994, pages: 182, note: 'a second volume of SubGenius scripture, alongside The Book of the SubGenius on the same shelf.' },
  { id: 115, type: 'book', title: 'Lolita', creator: 'Vladimir Nabokov', row: 2, col: 2, pos: 101, isbn13: '9780679723165', publisher: 'Vintage International', publish_year: 1989, pages: 317, note: 'first published 1955; shelved beside Pale Fire, Nabokov’s other novel here.', excerpt: 'Lolita, light of my life, fire of my loins. My sin, my soul.' },
  { id: 116, type: 'book', title: 'Mage: The Ascension', creator: 'White Wolf Publishing', row: 2, col: 4, pos: 101, isbn13: '9781565044005', publisher: 'White Wolf Publishing', publish_year: 1997, pages: 296, note: 'second-edition core rulebook — the tabletop game whose vocabulary (Awakening, Ascension, the numinous) runs underneath Scott’s own short story “Andrew Hawking” (structurally a Mage character backstory) and two of his own professional writing credits on this shelf, Blood Treachery and The Spirit Ways.' },
  { id: 117, type: 'book', title: 'Blood Treachery', creator: 'Scott Cohen & Steven DiPesa (White Wolf)', row: 2, col: 4, pos: 102, isbn13: '9781565044098', publisher: 'White Wolf Games Studio', publish_year: 2000, pages: 96, note: 'a Mage: The Ascension sourcebook Scott co-wrote professionally with Stephen Michael DiPesa. An earlier screenplay-format draft of this same book sits in Scott’s own archive — this is the version that shipped.' },
  { id: 118, type: 'book', title: 'The Spirit Ways: A Guide to Shamans and Spirituality in Mage: The Ascension', creator: 'Eric P. Taylor, Rachel Barth, Scott Cohen & John Snead (White Wolf)', row: 2, col: 1, pos: 101, isbn13: '9781565044531', publisher: 'White Wolf Games Studio', publish_year: 1999, pages: 136, note: 'another Mage: The Ascension sourcebook Scott co-wrote professionally, alongside Blood Treachery on the same shelf.' },
  { id: 119, type: 'book', title: 'Prometheus Rising', creator: 'Robert Anton Wilson', row: 1, col: 1, pos: 101, isbn13: '9780692710609', publisher: 'Hilaritas Press', publish_year: 2016, pages: 321, note: 'first published 1983; an eight-circuit model of consciousness built to be tried on rather than just read — Wilson’s own version of the physics-vs-feeling argument that 2001: A Space Odyssey, Solaris, and The Tree of Life stage as directors arguing with each other elsewhere on this shelf.' },
  { id: 120, type: 'book', title: 'Everything Is Under Control: Conspiracies, Cults, and Cover-Ups', creator: 'Robert Anton Wilson', row: 1, col: 2, pos: 101, isbn13: '9780061984310', publisher: 'HarperCollins', publish_year: 2009, pages: 456, note: 'first published 1998; an encyclopedia-format survey of conspiracy theories, cults, and secret societies — pattern-finding taken to its most maximalist extreme, the same impulse running through Gravity’s Rainbow and Borges’s Collected Fictions on this shelf. Patrick Harpur’s Daimonic Reality asks the harder version of the same question this book only surveys from outside.' },

  // Added 2026-07-23, mid-conversation, not from a shelf photo or a batch
  // of ISBNs but named one at a time as the conversation itself surfaced
  // them. Same randomized-placement rule as the July 23 batch above.
  { id: 121, type: 'book', title: 'Daimonic Reality: A Field Guide to the Otherworld', creator: 'Patrick Harpur', row: 1, col: 2, pos: 102, isbn13: '9780937663097', publisher: 'Pine Winds Press', publish_year: 2003, pages: 329, note: 'first published 1994 (Viking). Argues that daimons — fairies, apparitions, UFOs, visions — are neither literally real beings nor mere psychological projection, but a third category: real without being physical, disclosed through an imagination Harpur treats (via Henry Corbin’s mundus imaginalis) as a genuine perceptual faculty rather than a fantasy-generator. Gives an actual name and argument to the same blurred medium The Changing Light at Sandover’s Ouija board and the Symposium keep gesturing at without settling. Everything Is Under Control surveys the same territory from the outside; this book asks whether the choice between “real” and “made up” was ever the right question.' },
  { id: 122, type: 'book', title: 'Stories of Your Life and Others', creator: 'Ted Chiang', row: 1, col: 1, pos: 102, isbn13: '9781101972120', publisher: 'Vintage Books', publish_year: 2016, pages: 285, note: 'first published 2002. The second story, “Understand,” gives Physics vs. Ecstatics its cleanest fictional staging yet: a man undergoes an experimental treatment, cascades toward superintelligence, and chases a totalizing, self-transcendent understanding — pure computation and comprehension pushed to its ceiling, the same argument 2001: A Space Odyssey, Solaris, and The Tree of Life stage as directors arguing with each other, replayed here as plot — only to be undone not by a smarter version of the same axis, but by a second enhanced mind that never bothered with pure comprehension and instead mastered basic emotional manipulation. No amount of vertical climb on one axis buys safety from the axis nobody was watching.' },

  // Added 2026-07-23, a second batch of 25 ISBNs pasted in directly
  // ("More books:"). Same rule as both prior rounds: row/col/pos below
  // are arbitrary, spread across the existing book-only cubbies, not a
  // record of physical placement.
  { id: 123, type: 'book', title: 'The Glass Bead Game', creator: 'Hermann Hesse', row: 1, col: 1, pos: 103, isbn13: '9780312278496', publisher: 'Picador USA', publish_year: 2002, pages: 558, note: 'first published 1943 (as Das Glasperlenspiel); a monastic order spends its life perfecting a synthesis-game that unifies all of music, mathematics, and philosophy into a single symbolic language — Scott’s own decades-long ambition, voiced in Storyline.doc and elsewhere, to blend belief, science, magic, and perception into one overarching hypothesis, given a 20th-century German novel’s worth of scale.' },
  { id: 124, type: 'book', title: 'Tord Boontje', creator: 'Martina Margetts (ed.)', row: 2, col: 4, pos: 103, isbn13: '9780847829293', publisher: 'Rizzoli', publish_year: 2007, pages: 240, note: 'Scott, 2026-07-23, after this shelf went up: "I think one of the newer books got the wrong ISBN, the one you have listed as \'Swip Stolk.\' Correct for the real ISBN" — the ISBN search that produced "Swip Stolk" during the original cataloging round was simply wrong; this is the actual book, a monograph on the Dutch-born, UK-based designer’s lace-cut, organic product and lighting work (the Garland lightshade chief among it) — reference material, alongside the Alexander McQueen and Taschen volumes on this shelf, rather than something to be read start to finish.' },
  { id: 125, type: 'book', title: 'Collected Poems', creator: 'James Merrill', row: 2, col: 1, pos: 102, isbn13: '9780375411397', publisher: 'Knopf', publish_year: 2001, pages: 885, note: 'edited by J.D. McClatchy and Stephen Yenser; everything outside the Sandover trilogy — the shorter lyric poems Merrill wrote across the same decades he was holding the séances that became The Changing Light at Sandover, shelved a few cubbies away.' },
  { id: 126, type: 'book', title: 'Brave New World', creator: 'Aldous Huxley', row: 1, col: 2, pos: 103, isbn13: '9780060850524', publisher: 'Harper & Brothers', publish_year: 1932, note: 'a dystopia built on manufactured contentment rather than force — engineered stability instead of the engineered ecstasy Huxley would go looking for himself, decades later, in mescaline.' },
  { id: 127, type: 'book', title: 'Neuromancer', creator: 'William Gibson', row: 1, col: 1, pos: 104, isbn13: '9780441007462', publisher: 'Ace Books', publish_year: 2000, pages: 276, note: 'first published 1984; coined “cyberspace” and describes the Matrix as “a global consensus-hallucination” — the word Scott’s own 2003 cosmology-in-progress (Storyline.doc) explicitly refused to reuse for “the Surround” (“I cannot use the word matrix anymore, fuck you very much, Wachowski Brothers”), even though Gibson, not the Wachowskis, got there first.' },
  { id: 128, type: 'book', title: 'The Doors of Perception and Heaven and Hell', creator: 'Aldous Huxley', row: 1, col: 2, pos: 104, isbn13: '9780061729072', publisher: 'Harper Perennial', publish_year: 2009, pages: 208, note: 'first published 1954 and 1956; two essays on mescaline as a chemical key to “the Mind at Large,” Huxley’s own name for a wider reality ordinary perception filters down to almost nothing — a fourth name, after the Surround, the Umbra, and the chimerical, for the same threshold Harpur’s Daimonic Reality argues is disclosed rather than invented.' },
  { id: 129, type: 'book', title: 'Food of the Gods', creator: 'Terence McKenna', row: 1, col: 2, pos: 105, isbn13: '9780553371307', publisher: 'Bantam', publish_year: 1993, pages: 336, note: 'subtitled A Radical History of Plants, Drugs, and Human Evolution; McKenna’s case that psychedelic plants drove human consciousness itself — the same countercultural lineage as Prometheus Rising and Everything Is Under Control on this shelf, minus the jokes.' },
  { id: 130, type: 'book', title: 'The Planetary Omnibus', creator: 'Warren Ellis (art by John Cassaday)', row: 2, col: 3, pos: 102, isbn13: '9781401242381', publisher: 'DC Comics (WildStorm)', publish_year: 2014, pages: 864, note: 'collects the complete Planetary — “archaeologists of the impossible” excavating a secret pulp-fiction history hidden under the 20th century, structurally close to Scott’s own “Lament for the Future Never Realized” (Tesla, Verne, Wells, and Edison conspiring to vanish before their inventions are weaponized) and to the pattern-finding cluster this shelf already has running through Gravity’s Rainbow, Borges’s Collected Fictions, and Everything Is Under Control.' },
  { id: 131, type: 'book', title: 'The Cosmic Serpent: DNA and the Origins of Knowledge', creator: 'Jeremy Narby', row: 2, col: 1, pos: 103, isbn13: '9780874779646', publisher: 'Tarcher', publish_year: 1999, pages: 272, note: 'an anthropologist takes Amazonian shamans at their word that ayahuasca visions let them “see” molecular-level biological information directly — the Cosmic Serpent as one more name for the same imaginal perception Harpur’s Daimonic Reality argues for and Narby’s own scientific training tells him he shouldn’t take seriously.' },
  { id: 132, type: 'book', title: 'Trickster Makes This World: Mischief, Myth, and Art', creator: 'Lewis Hyde', row: 2, col: 2, pos: 102, isbn13: '9780374532550', publisher: 'Farrar, Straus and Giroux', publish_year: 2010, pages: 417, note: 'Hermes, Loki, Coyote, and Legba as a single figure who exists to cross boundaries that are supposed to be uncrossable — the mythological job description for everything else on this shelf that won’t stay on one side of the membrane: the Surround, the Umbra, the chimerical, the daimonic.' },
  { id: 133, type: 'book', title: 'The Kybalion: Hermetic Philosophy', creator: 'Three Initiates', row: 1, col: 2, pos: 106, isbn13: '9780143131687', publisher: 'TarcherPerigee', publish_year: 2018, pages: 176, note: 'first published 1908; seven Hermetic principles (“as above, so below” chief among them) presented as ancient Egyptian wisdom, almost certainly written by early-20th-century American occultists instead — shelved with Alchemy & Mysticism and the Library of Esoterica series, the same channeled-or-invented ambiguity running through all three.' },
  { id: 134, type: 'book', title: 'Kitchen Confidential', creator: 'Anthony Bourdain', row: 2, col: 4, pos: 104, isbn13: '9780060899226', publisher: 'Harper Perennial', publish_year: 2007, pages: 352, note: 'updated edition; a professional-kitchen memoir that built its author a bad-boy persona almost as durable as Wooderson’s drawl or Hedwig’s mythology, on this same shelf.' },
  { id: 135, type: 'book', title: 'The Invention of the Zero', creator: 'Richard Kenney', row: 2, col: 2, pos: 103, isbn13: '9780679749974', publisher: 'Knopf', publish_year: 1995, pages: 158, note: 'a poetry collection named for the moment nothing became a number — a mathematical Void that had to be invented before it could be worked with, sitting a few cubbies from Scott’s own decades-long argument with a Void of his own.' },
  { id: 136, type: 'book', title: 'The 39 Steps', creator: 'adapted by Patrick Barlow, from John Buchan and Hitchcock', row: 2, col: 3, pos: 103, isbn13: '9780573697142', publisher: 'Samuel French', publish_year: 2009, pages: 105, note: 'a stage adaptation that turns Hitchcock’s tense wrong-man thriller (also on this shelf) into a four-actor slapstick comedy, all 150-odd characters included — the same story surviving a third completely different container, after the novel and the film.' },
  { id: 137, type: 'book', title: 'The Squared Circle: Life, Death, and Professional Wrestling', creator: 'David Shoemaker', row: 2, col: 4, pos: 105, isbn13: '9781101609743', publisher: 'Avery', publish_year: 2013, note: 'a serious study of professional wrestling’s kayfabe — the collectively maintained fiction that scripted violence is real — as its own kind of belief technology, the same one The Book of the SubGenius runs as comedy and Everything Is Under Control runs as conspiracy.' },
  { id: 138, type: 'book', title: 'The Hobbit and The Lord of the Rings', creator: 'J.R.R. Tolkien', row: 2, col: 1, pos: 104, isbn13: '9780544445789', publisher: 'Houghton Mifflin Harcourt', pages: 1504, note: 'deluxe boxed set; the epic-relay thread already running from Homer through Virgil and Dante on this shelf gets a 20th-century entry that borrowed directly from all three.' },
  { id: 139, type: 'book', title: 'Holy Blood, Holy Grail', creator: 'Michael Baigent, Richard Leigh, and Henry Lincoln', row: 1, col: 1, pos: 105, isbn13: '9780385338455', publisher: 'Delta Trade Paperbacks', publish_year: 2004, pages: 489, note: 'first published 1982; speculative pseudohistory arguing for a hidden bloodline descending from Christ, treated as reference the same way this shelf treats the Library of Esoterica and Alchemy & Mysticism — pattern-finding indistinguishable, on the page, from research.' },
  { id: 140, type: 'book', title: 'Wiseguy', creator: 'Nicholas Pileggi', row: 2, col: 2, pos: 104, isbn13: '9781982129903', publisher: 'Simon & Schuster', publish_year: 2019, pages: 304, note: 'first published 1985; the true-crime source material for Goodfellas, an insider’s account of organized crime narrated with the same complicity-inducing charm the Coens’ small-time criminals never quite earn.' },
  { id: 141, type: 'book', title: 'Alexander McQueen: Savage Beauty', creator: 'Andrew Bolton', row: 2, col: 4, pos: 106, isbn13: '9781588394125', publisher: 'Metropolitan Museum of Art', publish_year: 2011, pages: 240, note: 'the catalog for the Met’s 2011 exhibition — a designer whose collections staged Gothic, exoticist, and naturalist mythologies as literal runway theater, reference material alongside Tord Boontje and the Taschen volumes here.' },
  { id: 142, type: 'book', title: 'The Godfather', creator: 'Mario Puzo', row: 2, col: 3, pos: 104, isbn13: '9781101043110', publisher: 'Penguin', note: 'first published 1969; the novel that gave organized crime its own code of honor and family loyalty, shelved near Wiseguy’s less mythologized, more panicked version of the same world.' },
  { id: 143, type: 'book', title: 'The Shining', creator: 'Stephen King', row: 1, col: 2, pos: 107, isbn13: '9780345806789', publisher: 'Anchor Books', publish_year: 2013, pages: 659, note: 'first published 1977; Kubrick’s 1980 adaptation is the same director’s coldness — the target of Tarkovsky’s “phony,” “pretensions to truth” complaint elsewhere on this shelf — turned on a haunted hotel instead of a monolith, with King himself famously on record disliking the result for exactly that reason.' },
  { id: 144, type: 'book', title: 'It’s Not About the Money', creator: 'Brent Kessel', row: 2, col: 1, pos: 105, isbn13: '9780061234064', publisher: 'HarperOne', publish_year: 2008, pages: 336, note: 'a personal-finance book built around eight “money types” and a spiritual, rather than purely tactical, approach to wealth.' },
  { id: 145, type: 'book', title: 'Decreation: Poetry, Essays, Opera', creator: 'Anne Carson', row: 2, col: 2, pos: 105, isbn13: '9781400078905', publisher: 'Vintage', publish_year: 2006, pages: 272, note: 'takes its title from Simone Weil’s term for undoing the self to make room for something larger — a third vocabulary, after Hedwig’s split and VALIS’s divided narrator, for a self coming apart on purpose rather than by accident.' },
  { id: 146, type: 'book', title: 'Snake ’n’ Bacon’s Cartoon Cabaret', creator: 'Michael Kupperman', row: 1, col: 1, pos: 106, isbn13: '9780380807901', publisher: 'HarperCollins', publish_year: 2000, note: 'absurdist comics starring a snake and a strip of bacon who have, per the strip’s own internal logic, been movie stars since the 1930s — a palette cleanser on a shelf that otherwise takes its own jokes fairly seriously.' },
  { id: 147, type: 'book', title: 'Nobilis, Livre de Base', creator: 'Jenna Katerin Moran (French edition)', row: 2, col: 3, pos: 105, isbn13: '9782970031406', publisher: 'Black Book Éditions', note: 'French translation of the tabletop RPG Nobilis, second edition; players anchor a Power — Death, the Sun, Entropy itself — into a human vessel and defend a plural, meaning-laden reality against the Excrucians, entities whose whole purpose is unmaking it into flat nothing. The clearest game-genre cousin yet to the Surround/Umbra/chimerical cluster: a system built entirely around a permeable membrane between the mundane and the numinous, and what it costs a person to stand at it.' },
];
