// The real bookshelf, cataloged from a photo (IMG_1202.jpeg) Scott took of
// his own shelf and asked to be scanned for every distinct book, film, and
// divination deck on it. See the library scene (src/scenes/library.js) for
// how this becomes a 3D shelf you can look around and click into.
//
// row/col/pos preserve the real shelf's layout — a 4x2 Kallax-style cube
// shelf, row 1 on top — and pos is left-to-right order within that cubby,
// so the scene lays these out in the same order they actually sit in
// Scott's apartment.
//
// A first pass at this catalog was built from the wrong source photo
// (IMG_1192.jpeg, a distorted panorama); this is the corrected version,
// re-read directly from IMG_1202.jpeg (5712x4284, straight-on).
export const libraryItems = [
  { id: 1, type: 'book', title: 'Beowulf', creator: 'trans. unattributed on spine', row: 1, col: 1, pos: 0 },
  { id: 2, type: 'book', title: 'Shinto: The Kami Way', creator: 'Sokyo Ono', row: 1, col: 1, pos: 1 },
  { id: 3, type: 'book', title: 'Água Viva', creator: 'Clarice Lispector', row: 1, col: 1, pos: 2 },
  { id: 4, type: 'book', title: 'Tao Te Ching', creator: 'Lao Tzu', row: 1, col: 1, pos: 3 },
  { id: 5, type: 'book', title: 'Faust', creator: 'Johann Wolfgang von Goethe', row: 1, col: 1, pos: 4 },
  { id: 6, type: 'book', title: 'Alchemy & Mysticism', creator: 'Alexander Roob (Taschen)', row: 1, col: 1, pos: 5 },
  { id: 7, type: 'book', title: 'The Canterbury Tales', creator: 'Geoffrey Chaucer', row: 1, col: 2, pos: 0 },
  { id: 8, type: 'book', title: 'Paradise Lost', creator: 'John Milton', row: 1, col: 2, pos: 1 },
  { id: 9, type: 'book', title: 'Medea and Other Plays', creator: 'Euripides', row: 1, col: 2, pos: 2 },
  { id: 10, type: 'book', title: 'The Bacchae and Other Plays', creator: 'Euripides', row: 1, col: 2, pos: 3 },
  { id: 11, type: 'book', title: 'A Portrait of the Artist as a Young Man', creator: 'James Joyce', row: 1, col: 2, pos: 4 },
  { id: 12, type: 'book', title: 'The Republic', creator: 'Plato', row: 1, col: 2, pos: 5 },
  { id: 13, type: 'book', title: 'The Symposium', creator: 'Plato', row: 1, col: 2, pos: 6 },
  { id: 14, type: 'book', title: 'Phaedrus', creator: 'Plato', row: 1, col: 2, pos: 7 },
  { id: 15, type: 'book', title: 'The Last Days of Socrates', creator: 'Plato', row: 1, col: 2, pos: 8 },
  { id: 16, type: 'book', title: 'The Epic of Gilgamesh', creator: '', row: 1, col: 2, pos: 9 },
  { id: 17, type: 'book', title: 'The Theban Plays', creator: 'Sophocles', row: 1, col: 2, pos: 10 },
  { id: 18, type: 'book', title: 'Lysistrata and Other Plays', creator: 'Aristophanes', row: 1, col: 2, pos: 11 },
  { id: 19, type: 'book', title: 'Leaves of Grass', creator: 'Walt Whitman', row: 1, col: 2, pos: 12 },
  { id: 20, type: 'book', title: 'Bhagavad Gita', creator: '', row: 1, col: 2, pos: 13 },
  { id: 21, type: 'book', title: 'Buddhist Scriptures', creator: '', row: 1, col: 2, pos: 14 },
  { id: 22, type: 'book', title: 'Oresteia', creator: 'Aeschylus', row: 1, col: 2, pos: 15 },
  { id: 23, type: 'book', title: 'Songs of Innocence and Experience', creator: 'William Blake', row: 1, col: 2, pos: 16 },
  { id: 24, type: 'book', title: 'Meditations', creator: 'Marcus Aurelius', row: 1, col: 2, pos: 17 },
  { id: 25, type: 'book', title: 'Chaos: Making a New Science', creator: 'James Gleick', row: 1, col: 2, pos: 18 },
  { id: 26, type: 'book', title: 'The Homeric Hymns', creator: '', row: 1, col: 2, pos: 19 },
  { id: 27, type: 'bluray', title: 'The Princess Bride', creator: 'dir. Rob Reiner (Criterion)', row: 1, col: 2, pos: 20 },
  { id: 28, type: 'book', title: 'Three Colours Trilogy: Blue White Red (companion volume)', creator: 'Krzysztof Kieślowski', row: 1, col: 2, pos: 21 },
  { id: 29, type: 'dvd', title: 'Dekalog', creator: 'Krzysztof Kieślowski · Criterion 637', row: 1, col: 3, pos: 0 },
  { id: 30, type: 'dvd', title: 'Do the Right Thing', creator: 'Spike Lee · Criterion 97', row: 1, col: 3, pos: 1 },
  { id: 31, type: 'dvd', title: 'Seven Samurai', creator: 'Akira Kurosawa · Criterion 2', row: 1, col: 3, pos: 2 },
  { id: 32, type: 'dvd', title: 'Danger: Diabolik', creator: 'Mario Bava · Criterion 356', row: 1, col: 3, pos: 3 },
  { id: 33, type: 'dvd', title: 'The Tree of Life', creator: 'Terrence Malick · Criterion 942', row: 1, col: 3, pos: 4 },
  { id: 34, type: 'dvd', title: "A Hard Day's Night", creator: 'dir. Richard Lester · Criterion 1104', row: 1, col: 3, pos: 5 },
  { id: 35, type: 'dvd', title: 'Citizen Kane', creator: 'Orson Welles', row: 1, col: 3, pos: 6 },
  { id: 36, type: 'dvd', title: 'The Silence of the Lambs', creator: 'Jonathan Demme · Criterion 13', row: 1, col: 3, pos: 7 },
  { id: 37, type: 'dvd', title: 'Dr. Strangelove', creator: 'Stanley Kubrick · Criterion 821', row: 1, col: 3, pos: 8 },
  { id: 38, type: 'dvd', title: 'Blow-Up', creator: 'Michelangelo Antonioni · Criterion 845', row: 1, col: 3, pos: 9 },
  { id: 39, type: 'dvd', title: 'Repo Man', creator: 'Alex Cox · Criterion 534', row: 1, col: 3, pos: 10 },
  { id: 40, type: 'dvd', title: 'Hedwig and the Angry Inch', creator: 'John Cameron Mitchell · Criterion 593', row: 1, col: 3, pos: 11 },
  { id: 41, type: 'dvd', title: 'Throne of Blood', creator: 'Akira Kurosawa', row: 1, col: 3, pos: 12 },
  { id: 42, type: 'dvd', title: 'Malcolm X', creator: 'Spike Lee · Criterion 740', row: 1, col: 3, pos: 13 },
  { id: 43, type: 'dvd', title: 'Inside Llewyn Davis', creator: 'Joel & Ethan Coen · Criterion 794', row: 1, col: 3, pos: 14 },
  { id: 44, type: 'dvd', title: 'Dreams', creator: 'Akira Kurosawa · Criterion 842', row: 1, col: 3, pos: 15 },
  { id: 45, type: 'dvd', title: 'The 39 Steps', creator: 'Alfred Hitchcock · Criterion 56', row: 1, col: 3, pos: 16 },
  { id: 46, type: 'dvd', title: 'La Jetée / Sans Soleil', creator: 'Chris Marker · Criterion 387', row: 1, col: 3, pos: 17 },
  { id: 47, type: 'dvd', title: 'Blood Simple', creator: 'Joel & Ethan Coen (Criterion)', row: 1, col: 4, pos: 0 },
  { id: 48, type: 'dvd', title: 'All That Jazz', creator: 'Bob Fosse (Criterion)', row: 1, col: 4, pos: 1 },
  { id: 49, type: 'dvd', title: 'No Country for Old Men', creator: 'Joel & Ethan Coen (Criterion)', row: 1, col: 4, pos: 2 },
  { id: 50, type: 'dvd', title: 'Double Indemnity', creator: 'Billy Wilder (Criterion)', row: 1, col: 4, pos: 3 },
  { id: 51, type: 'dvd', title: 'Tokyo Story', creator: 'Yasujiro Ozu (Criterion)', row: 1, col: 4, pos: 4 },
  { id: 52, type: 'dvd', title: '8½', creator: 'Federico Fellini (Criterion)', row: 1, col: 4, pos: 5 },
  { id: 53, type: 'dvd', title: 'Solaris', creator: 'Andrei Tarkovsky (Criterion)', row: 1, col: 4, pos: 6 },
  { id: 54, type: 'dvd', title: 'Ghost Dog: The Way of the Samurai', creator: 'Jim Jarmusch (Criterion)', row: 1, col: 4, pos: 7 },
  { id: 55, type: 'dvd', title: 'F for Fake', creator: 'Orson Welles (Criterion)', row: 1, col: 4, pos: 8 },
  { id: 56, type: 'dvd', title: "Miller's Crossing", creator: 'Joel & Ethan Coen (Criterion)', row: 1, col: 4, pos: 9 },
  { id: 57, type: 'bluray', title: 'The Right Stuff', creator: 'Philip Kaufman (Kino Lorber Studio Classics)', row: 1, col: 4, pos: 10 },
  { id: 58, type: 'bluray', title: 'Barton Fink', creator: 'Joel & Ethan Coen', row: 1, col: 4, pos: 11 },
  { id: 59, type: 'bluray', title: 'The Maya Deren Collection', creator: '', row: 1, col: 4, pos: 12 },
  { id: 60, type: 'bluray', title: 'North by Northwest', creator: 'Alfred Hitchcock (4K UHD)', row: 1, col: 4, pos: 13 },
  { id: 61, type: 'bluray', title: 'Vertigo', creator: 'Alfred Hitchcock (4K UHD)', row: 1, col: 4, pos: 14 },
  { id: 62, type: 'bluray', title: 'GoodFellas', creator: 'Martin Scorsese (4K UHD)', row: 1, col: 4, pos: 15 },
  { id: 63, type: 'bluray', title: '2001: A Space Odyssey', creator: 'Stanley Kubrick, 50th Anniversary Edition (4K UHD)', row: 1, col: 4, pos: 16 },
  { id: 64, type: 'bluray', title: 'Fargo', creator: 'Joel & Ethan Coen, 2-disc set (4K UHD)', row: 1, col: 4, pos: 17 },
  { id: 65, type: 'bluray', title: 'The Big Lebowski', creator: 'Joel & Ethan Coen (4K UHD)', row: 1, col: 4, pos: 18 },
  { id: 66, type: 'bluray', title: 'Close Encounters of the Third Kind', creator: 'Steven Spielberg (4K UHD)', row: 1, col: 4, pos: 19 },
  { id: 67, type: 'bluray', title: 'Chinatown', creator: 'Roman Polanski (4K UHD)', row: 1, col: 4, pos: 20 },
  { id: 68, type: 'bluray', title: 'Reservoir Dogs', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 21 },
  { id: 69, type: 'bluray', title: 'Pulp Fiction', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 22 },
  { id: 70, type: 'bluray', title: 'Kill Bill Vol. 1', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 23 },
  { id: 71, type: 'bluray', title: 'Kill Bill Vol. 2', creator: 'Quentin Tarantino (4K UHD)', row: 1, col: 4, pos: 24 },
  { id: 72, type: 'book', title: 'Rosencrantz & Guildenstern Are Dead', creator: 'Tom Stoppard', row: 2, col: 1, pos: 0 },
  { id: 73, type: 'book', title: 'Gödel, Escher, Bach: An Eternal Golden Braid', creator: 'Douglas R. Hofstadter', row: 2, col: 1, pos: 1 },
  { id: 74, type: 'book', title: 'wabi sabi: Understanding the Zen Philosophy of Beauty', creator: 'Andrew Juniper (Tuttle)', row: 2, col: 1, pos: 2 },
  { id: 75, type: 'book', title: 'In Praise of Shadows', creator: "Jun'ichirō Tanizaki", row: 2, col: 1, pos: 3 },
  { id: 76, type: 'book', title: 'Kieślowski on Kieślowski', creator: 'ed. Danusia Stok', row: 2, col: 1, pos: 4 },
  { id: 77, type: 'book', title: 'Three Colours Trilogy: Blue, White, Red (screenplays)', creator: 'Krzysztof Kieślowski & Krzysztof Piesiewicz', row: 2, col: 1, pos: 5 },
  { id: 78, type: 'book', title: "Gravity's Rainbow", creator: 'Thomas Pynchon', row: 2, col: 1, pos: 6 },
  { id: 79, type: 'book', title: 'Collected Fictions', creator: 'Jorge Luis Borges (Penguin Classics Deluxe)', row: 2, col: 1, pos: 7 },
  { id: 80, type: 'book', title: 'The Iliad', creator: 'Homer, trans. Robert Fagles (Penguin Classics Deluxe)', row: 2, col: 1, pos: 8 },
  { id: 81, type: 'book', title: 'The Odyssey', creator: 'Homer, trans. Robert Fagles (Penguin Classics Deluxe)', row: 2, col: 1, pos: 9 },
  { id: 82, type: 'book', title: 'The Aeneid', creator: 'Virgil, trans. Robert Fagles (Penguin Classics Deluxe)', row: 2, col: 1, pos: 10 },
  { id: 83, type: 'book', title: 'Dune', creator: 'Frank Herbert', row: 2, col: 2, pos: 0 },
  { id: 84, type: 'book', title: 'The Complete Stories', creator: 'Clarice Lispector', row: 2, col: 2, pos: 1 },
  { id: 85, type: 'book', title: 'Ulysses', creator: 'James Joyce', row: 2, col: 2, pos: 2 },
  { id: 86, type: 'book', title: '1Q84', creator: 'Haruki Murakami', row: 2, col: 2, pos: 3 },
  { id: 87, type: 'book', title: 'Near to the Wild Heart', creator: 'Clarice Lispector', row: 2, col: 2, pos: 4 },
  { id: 88, type: 'book', title: 'The Crying of Lot 49', creator: 'Thomas Pynchon', row: 2, col: 2, pos: 5 },
  { id: 89, type: 'book', title: 'Finnegans Wake', creator: 'James Joyce', row: 2, col: 2, pos: 6 },
  { id: 90, type: 'book', title: 'The Metamorphoses', creator: "Ovid (Everyman's Library)", row: 2, col: 2, pos: 7 },
  { id: 91, type: 'book', title: 'The Divine Comedy', creator: "Dante Alighieri (Everyman's Library)", row: 2, col: 2, pos: 8 },
  { id: 92, type: 'book', title: 'Japanese Woodblock Prints, 1680–1938', creator: 'Andreas Marks (Taschen 40 series)', row: 2, col: 3, pos: 0 },
  { id: 93, type: 'book', title: 'The Book of Symbols: Reflections on Archetypal Images', creator: 'Archive for Research in Archetypal Symbolism (Taschen)', row: 2, col: 3, pos: 1 },
  { id: 94, type: 'book', title: 'The Beastie Boys Book', creator: 'Michael Diamond & Adam Horovitz (Spiegel & Grau)', row: 2, col: 3, pos: 2 },
  { id: 95, type: 'book', title: 'The Library of Esoterica: Sacred Sites', creator: 'Taschen', row: 2, col: 3, pos: 3 },
  { id: 96, type: 'book', title: 'The Library of Esoterica: Astrology', creator: 'Taschen', row: 2, col: 3, pos: 4 },
  { id: 97, type: 'book', title: 'The Library of Esoterica: Plant Magick', creator: 'Taschen', row: 2, col: 3, pos: 5 },
  { id: 98, type: 'book', title: 'The Library of Esoterica: Tarot', creator: 'Taschen', row: 2, col: 3, pos: 6 },
  { id: 99, type: 'divination_box', title: 'The Wild Unknown Tarot', creator: 'Kim Krans', row: 2, col: 3, pos: 7 },
  { id: 100, type: 'divination_box', title: 'The Wild Unknown Alchemy', creator: 'Kim Krans', row: 2, col: 3, pos: 8 },
  { id: 101, type: 'book', title: 'The Library of Esoterica: Witchcraft', creator: 'Taschen', row: 2, col: 4, pos: 0 },
  { id: 102, type: 'book', title: 'William Shakespeare: Complete Works', creator: 'ed. Jonathan Bate & Eric Rasmussen, RSC 2nd ed. (Modern Library)', row: 2, col: 4, pos: 1 },
  { id: 103, type: 'book', title: 'The Lyrics: 1956 to the Present', creator: 'Paul McCartney, ed. Paul Muldoon (Liveright)', row: 2, col: 4, pos: 2 },
  { id: 104, type: 'book', title: 'Art of Atari', creator: 'Tim Lapetino (Dynamite)', row: 2, col: 4, pos: 3 },
  { id: 105, type: 'book', title: 'The French Laundry Cookbook', creator: 'Thomas Keller (Artisan)', row: 2, col: 4, pos: 4 },
  { id: 106, type: 'book', title: 'The French Laundry, Per Se', creator: 'Thomas Keller (Artisan)', row: 2, col: 4, pos: 5 },
  { id: 107, type: 'book', title: 'Expanding Universe: Photographs from the Hubble Space Telescope', creator: 'Taschen', row: 2, col: 4, pos: 6 },
];
