


export const SCENES = {
  sphere:    { tile: 1.12, nudge: -0.045,
               exportName: 'createSphere',
               label: 'sphere',
               blurb: 'sphere',
               controls: 'Drag to orbit, click a facet to read.' },
  butterfly: { tile: 0.90, nudge: 0.05,
               exportName: 'createButterfly',
               label: 'butterfly',
               overlayBg: '#000000',
               blurb: 'butterfly',
               controls: 'Drag to orbit, scroll to zoom.' },
  scroll:    { tile: 1.02, nudge: 0.03,
               exportName: 'createScroll',
               label: 'scroll',
               blurb: 'a scroll',
               controls: 'Scroll to read.' },
  theater:   { tile: 1.06, nudge: -0.02,
               exportName: 'createTheater',
               label: 'theater',
               blurb: 'theater',
               controls: 'A different program each visit; click or use the controls to advance.' },
  orbiter:   { tile: 0.92, nudge: -0.05,
               exportName: 'createOrbiter',
               label: 'orbiter',
               blurb: 'orbiter',
               controls: 'Drag to orbit, click a satellite to read a poem, click the nucleus to look inside.' },
  orrery:    { tile: 1.00, nudge: 0.04,
               exportName: 'createOrrery',
               label: 'orrery',
               blurb: 'orrery',
               controls: 'Walk with the arrow keys or WASD, click to look around, click the control box or a flyer to read.' },
  library:   { tile: 1.10, nudge: -0.03,
               exportName: 'createLibrary',
               label: 'library',
               blurb: 'library',
               controls: 'Drag to orbit, scroll to zoom, click a spine to read what it is, click a CD to watch.' },
  beamline:  { tile: 0.91, nudge: 0.05,
               exportName: 'createBeamline',
               label: 'beamline',
               blurb: 'beamline',
               controls: 'Drag to orbit, scroll to zoom, click a station to read.' },
  harmonics: { tile: 0.94, nudge: -0.04,
               exportName: 'createharmonics',
               label: 'harmonics',
               blurb: 'harmonics',
               controls: 'Drag to orbit, scroll to zoom, touch a node.' },
  outside:   { tile: 1.08, nudge: 0.025,
               exportName: 'createOutside',
               label: 'outside',
               blurb: 'outside',
               controls: 'Drag to orbit, scroll to zoom, touch a petal.' },
  apollo:    { tile: 0.97, nudge: -0.05,
               exportName: 'createApollo',
               label: 'apollo',
               blurb: 'apollo',
               controls: 'Move a fader to put an element into the light, click a dark line to hear its wavelength as a pitch.' },
  psyshell:  { tile: 0.93, nudge: 0.04,
               exportName: 'createPsyshell',
               label: 'psyshell',
               blurb: 'psyshell',
               controls: 'Drag to turn it, scroll to zoom, point the lightpen at it to read one sentence and watch the light of its number travel through the crystal.' },
  medium:    { tile: 1.12, nudge: -0.025,
               exportName: 'createMedium',
               label: 'medium',
               blurb: 'medium',
               controls: 'Press on the cup and rest your hand; nothing moves until you do, and nothing moves once you let go. Letters land while you are touching it and fill a tape along the bottom.' },
  quiz:      { tile: 1.04, nudge: 0.02,
               exportName: 'createQuiz',
               label: 'quiz',
               blurb: 'quiz',
               controls: 'Answer all sixteen and press the button. Everything after that happens on its own.' },

};


export const sceneAria = spec => `${spec.blurb} ${spec.controls}`;
export const tileAria  = spec => `${spec.blurb}`;

export const TEXT_EXEMPT = {
  butterfly: 'Its entire found text is its own placard title, which the landing page already carries.',
  harmonics: 'It publishes no text of its own — it is a view of the connections between other scenes, each of which has its own page.',
  outside:   'Its text is 19 proper names — five Sources of Power, their Folk Origins, Magi and Psi — laid out as a diagram rather than written as prose. There is no passage to publish, only labels on a flower.',
};
