


export const SCENES = {
  sphere:    { tile: 1.12, nudge: -0.045,
               exportName: 'createSphere',
               label: 'The Sphere — full screen experience. Press Escape to return.',
               blurb: 'The Sphere — an interactive geodesic sphere with text fragments.',
               controls: 'Drag to orbit, click a facet to read.' },
  butterfly: { tile: 0.90, nudge: 0.05,
               exportName: 'createButterfly',
               label: 'Chaos Butterfly in Phase Space, 2026.',
               overlayBg: '#000000',
               blurb: 'Chaos Butterfly in Phase Space, 2026 — a Lorenz attractor visualization.',
               controls: 'Drag to orbit, scroll to zoom.' },
  scroll:    { tile: 1.02, nudge: 0.03,
               exportName: 'createScroll',
               label: 'Selected Works — A Scroll of Found Writing.',
               blurb: 'Selected Works — a scroll of found writing, carved fragments, 2000 to 2012.',
               controls: 'Scroll to read.' },
  theater:   { tile: 1.06, nudge: -0.02,
               exportName: 'createTheater',
               label: 'The Theater — Now Playing.',
               blurb: 'The Theater — scenes from Truth and Beauty, Paul Revere, and You’ve Got a Friend in Satan, performed by ASCII actors.',
               controls: 'A different program each visit; click or use the controls to advance.' },
  orbiter:   { tile: 0.92, nudge: -0.05,
               exportName: 'createOrbiter',
               label: 'Orbiter — A p-Orbital, Satellites.',
               blurb: 'Orbiter — a hydrogen atom’s p-orbital rendered as a fuzzy probability cloud, with satellites in clean elliptical orbits around it.',
               controls: 'Drag to orbit, click a satellite to read a poem, click the nucleus to look inside.' },
  orrery:    { tile: 1.00, nudge: 0.04,
               exportName: 'createOrrery',
               label: 'The Orrery of Los Feliz.',
               blurb: 'The Orrery of Los Feliz — a found story, told through a 30-foot orrery: nine planets, their moons, an asteroid belt, in a warehouse you can walk around.',
               controls: 'Walk with the arrow keys or WASD, click to look around, click the control box or a flyer to read.' },
  library:   { tile: 1.10, nudge: -0.03,
               exportName: 'createLibrary',
               label: 'The Library — once removed.',
               blurb: 'The Library — a real bookshelf of books, films and divination decks, rebuilt as a shelf you can turn in space.',
               controls: 'Drag to orbit, scroll to zoom, click a spine to read what it is, click a CD to watch.' },
  beamline:  { tile: 0.91, nudge: 0.05,
               exportName: 'createBeamline',
               label: 'Beamline.',
               blurb: 'Beamline — a small vessel travelling a glowing rail across a night wilderness, with ten stations along it, each holding a fragment of found text.',
               controls: 'Drag to orbit, scroll to zoom, click a station to read.' },
  harmonics: { tile: 0.94, nudge: -0.04,
               exportName: 'createharmonics',
               label: 'Harmonics.',
               blurb: 'Harmonics — resonant pieces across every other scene, laid out by how strongly they connect and pulsing in sync with whatever they resonate with.',
               controls: 'Drag to orbit, scroll to zoom, touch a node.' },
  outside:   { tile: 1.08, nudge: 0.025,
               exportName: 'createOutside',
               label: 'Outside.',
               blurb: 'Outside — a generated lotus mapping the five Sources of Power as petals and their Folk Origins, Magi and Psi at the center, breathing continuously on its own.',
               controls: 'Drag to orbit, scroll to zoom, touch a petal.' },
  apollo:    { tile: 0.97, nudge: -0.05,
               exportName: 'createApollo',
               label: 'Apollo — an absorption spectrum you can play.',
               blurb: 'Apollo — a solar absorption spectrum you can play: a band of starlight with dark lines missing from it, and a corona streaming past.',
               controls: 'Move a fader to put an element into the light, click a dark line to hear its wavelength as a pitch.' },
  psyshell:  { tile: 0.93, nudge: 0.04,
               exportName: 'createPsyshell',
               label: 'Psyshell — lens RE73415.',
               blurb: 'Psyshell — a small crystal antler suspended in a web of fine filaments, holding every sentence on this site as a point of light inside it. The web and the object are one structure at two scales.',
               controls: 'Drag to turn it, scroll to zoom, point the lightpen at it to read one sentence and watch the light of its number travel through the crystal.' },
  medium:    { tile: 1.12, nudge: -0.025,
               exportName: 'createMedium',
               label: 'Medium — a board that can spell.',
               blurb: 'Medium — a homemade Ouija board seen from above, with an upside-down teacup on it and two pairs of fingertips: yours and somebody else’s.',
               controls: 'Press on the cup and rest your hand; nothing moves until you do, and nothing moves once you let go. Letters land while you are touching it and fill a tape along the bottom.' },
  quiz:      { tile: 1.04, nudge: 0.02,
               exportName: 'createQuiz',
               label: 'Quiz — sixteen questions, and then a judgment.',
               blurb: 'Quiz — a short questionnaire of the ordinary kind, and then a verdict about you delivered at some volume by a system that did not ask, does not hedge, and is not taking questions.',
               controls: 'Answer all sixteen and press the button. Everything after that happens on its own.' },

};


export const sceneAria = spec => `${spec.blurb} ${spec.controls}`;
export const tileAria  = spec => `${spec.blurb} Press Enter to expand.`;

export const TEXT_EXEMPT = {
  butterfly: 'Its entire found text is its own placard title, which the landing page already carries.',
  harmonics: 'It publishes no text of its own — it is a view of the connections between other scenes, each of which has its own page.',
  outside:   'Its text is 19 proper names — five Sources of Power, their Folk Origins, Magi and Psi — laid out as a diagram rather than written as prose. There is no passage to publish, only labels on a flower.',
};
